if [[ $COLORTERM == gnome-* && $TERM == xterm  ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

export DOTFILES=$HOME/.dotfiles
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="ys"
plugins=(git)

source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/functions.zsh

source $HOME/.xinitrc

if [ -n "$PS1"   ]; then 
    eval "$(~/.dotfiles/colorschemes/base16-builder/profile_helper.sh)" 
fi

source $DOTFILES/zsh/environment.zsh
